<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Блог обо всем</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="../../../styles/gate.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Блог обо всем</h1>
        </div>
        <div class="col-12 info-message justify-content-center align-items-center">
            <span class="col-1 badge bg-warning text-dark">Warning</span>
            <p class="col-11">Пользоваться блогом могут только авторизованные пользователи. Если вы впервые у нас, то зарегистрируйтесь в форме внизу и слева. Если уже имеете учетную запись, то войдите через форму справа.</p>
        </div>
        <div class="row align-items-start justify-content-center">
            <div class="col-4">
                <h2>Регистрация</h2>
                <form action="/user/register" method="post">
                    <label for="InputEmail" class="form-label">Email:</label>
                    <input type="email" name="email" class="form-control" id="InputEmail">

                    <label for="InputName" class="form-label">Имя:</label>
                    <input type="text" name="name" class="form-control" id="InputName">

                    <label for="InputName" class="form-label">Пароль:</label>
                    <input type="password" name="password" class="form-control" id="InputPass" aria-describedby="passHelp1">
                    <div id="passHelp1" class="form-text">Не менее 4 символов</div>

                    <label for="InputName" class="form-label">Еще раз пароль:</label>
                    <input type="password" name="passwordRetry" class="form-control" id="InputPass" aria-describedby="passHelp2">
                    <div id="passHelp2" class="form-text">Нужно ввести пароль повторно для проверки</div>
                    <br>
                    <input type="submit" class="btn btn-primary" value="Зарегистрироваться">
                </form>
                <br>
            </div>
            <div class="col-4">
                <h2>Войти</h2>
                <form action="/user/login" method="post">
                    <label for="InputEmail2" class="form-label">Email:</label>
                    <input type="email" name="email" class="form-control" id="InputEmail2">

                    <label for="InputName" class="form-label">Пароль:</label>
                    <input type="password" name="password" class="form-control" id="InputPass">
                    <br>
                    <input type="submit" class="btn btn-primary" value="Войти">
                </form>
                <a href="newPassword">Забыли пароль?</a>
                <br>
                <br>
                <br>
                <?php if($this->error): ?>
                    <span style="color: red"><?=$this->error;?></span>
                <?php endif; ?>
            </div>

        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>
